version: '3.8'

services:
  backend:
    image: airyou/prompthub:nutrition-bot
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 3
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - nut_bot-network

  db:
    image: postgres:16
    ports:
      - '15434:5432'
    env_file:
      - .env
    volumes:
      - ./postgres16:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nut_bot-network
  
  redis:
    image: redis:7.4.2
    command: redis-server --requirepass 12345678 --protected-mode yes
    ports:
      - '16379:6379'
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -a 12345678 ping | grep -q PONG']
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - nut_bot-network

networks:
  nut_bot-network:
