"""Add user personal parameters for nutrition calculation

Revision ID: 64ef96158639
Revises: 0868174e045c
Create Date: 2025-07-14 15:26:37.360207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ef96158639'
down_revision: Union[str, Sequence[str], None] = '0868174e045c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('telegram_users', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('telegram_users', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('telegram_users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('telegram_users', sa.Column('activity_level', sa.String(length=20), nullable=True))
    op.add_column('telegram_users', sa.Column('goal', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'goal')
    op.drop_column('telegram_users', 'activity_level')
    op.drop_column('telegram_users', 'gender')
    op.drop_column('telegram_users', 'height')
    op.drop_column('telegram_users', 'weight')
    op.drop_column('telegram_users', 'age')
    # ### end Alembic commands ###
